# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="juanghurtado"
#ZSH_THEME="mortalscumbag"
#ZSH_THEME="trapd00r"
ZSH_THEME="sunrise"
#ZSH_THEME="bureau"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-extras mercurial archlinux cabal common-aliases battery)

source $ZSH/oh-my-zsh.sh
source ~/.zsh/cb.sh

# Customize to your needs...

export TERM=xterm-256color
export SSH_AUTH_SOCK=0

alias ls='ls -Fsbh --color=always'
#alias rm='rm -i'
alias rm='gio trash'
alias remake='make clean; make'
alias time=/usr/bin/time
alias clock="~/bin/clock ~/.punchcard"
alias vim=nvim

export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
export PATH=~/.cargo/bin:$PATH
export PATH=~/.usr/bin:$PATH
export PATH=~/.usr/local/bin:$PATH
export PATH=/opt/matlab/bin:$PATH
export PATH=~/.usr/npm/bin:$PATH

export GREP_OPTIONS=""
export LIBGL_DEBUG=verbose
export MESA_DEBUG
export GOPATH=~
#export RUST_SRC_PATH=~/src/rust/src
export RUST_SRC_PATH=~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
export RUST_BACKTRACE=t
export MOZ_USE_XINPUT2=1
export _JAVA_AWT_WM_NONREPARENTING=1
export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH

source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

command fortune -ae

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

. /home/sam/programs/miniconda3/etc/profile.d/conda.sh

export CONDA_PROJECT_ROOT="$HOME/conda"

# tmux a -t 0

eval "$(starship init zsh)"
