source ${HOME}/.zsh/antigen.zsh

antigen use oh-my-zsh

#antigen theme juanghurtado
#antigen theme mortalscumbag
#antigen theme trapd00r
antigen theme sunrise
#antigen theme bureau

antigen bundle git
antigen bundle git-extras
antigen bundle common-aliases
antigen bundle pip
antigen bundle archlinux
antigen bundle battery
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

antigen apply

#
# Customize to your needs...
#

source ${HOME}/.zsh/cb.sh

export TERM=xterm-256color
export SSH_AUTH_SOCK=0

alias ls='ls -Fsbh --color=always'
#alias rm='rm -i'
alias rm='gio trash'
#alias time=/usr/bin/time

export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
export PATH=~/.cargo/bin:$PATH
export PATH=~/.usr/bin:$PATH
export PATH=~/.usr/local/bin:$PATH
export PATH=/opt/matlab/bin:$PATH
export PATH=~/.usr/npm/bin:$PATH

export LIBGL_DEBUG=verbose
export MESA_DEBUG
export RUST_SRC_PATH=~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
export RUST_BACKTRACE=t
export MOZ_USE_XINPUT2=1
export _JAVA_AWT_WM_NONREPARENTING=1
export LD_LIBRARY_PATH=/usr/local/lib/:/opt/openmm/openmm74/lib:$LD_LIBRARY_PATH

. /home/sam/programs/miniconda3/etc/profile.d/conda.sh
export CONDA_PROJECT_ROOT="$HOME/conda"

if [ -e /home/sam/.nix-profile/etc/profile.d/nix.sh ]; then . /home/sam/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

command fortune -ae
